---
- name: Install Packages.
  become: true
  hosts: all
  tasks:
    - name: Install EPEL.
      yum:
        name:
          - epel-release
        state: present
    - name: Install git, htop, tree and vim.
      yum:
        name:
          - git
          - htop
          - tree
          - vim
        state: latest
